FROM golang:1.12.6-alpine

# Install git
RUN set -ex; \
    apk update; \
    apk add --no-cache git

# Set working directory
MKDIR /project
ADD . /project
WORKDIR /project

# Run tests
CMD CGO_ENABLED=0 go test ./...